spring:
  application:
    name: gateway-web

  # 跨域问题
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_user_route
          #uri: http://localhost:18088
          uri: lb://user
          predicates:
            - Path=/user/**,/address/**,/areas/**,/cities/**,/provinces/**


        # 唯一标识符
        - id: changgou_goods_route
          # 路由到什么地址
          uri: http://localhost:18081
          # uri: lb://goods  # lb://微服务名称
          predicates:
            # - Host=cloud.itheima.com**   # host过滤
            - Path=/album/**,/brand/**,/cache/**,/categoryBrand/**,/category/**,/para/**,/pref/**,/sku/**,/spec/**,/spu/**,/stockBack/**,/template/**
#           - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#             args:
#               key-resolver: "#{@ipKeyResolver}"
#               # 每秒钟只允许有1个请求
#               redis-rate-limiter.replenishRate: 1
#               # 宽限数量
#               redis-rate-limiter.burstCapacity: 1
  #Redis配置
  redis:
    host: 192.168.211.132
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true